ktor:
  application:
    modules:
      - pl.rafapp.ApplicationKt.module
  deployment:
    port: 8080

# Konfiguracja Ollamy
ollama:
  url: "http://localhost:11434"
  model: "bielik:latest"

# Konfiguracja poczty
mail:
  host: "imap.marpol.pl"
  port: 993
  username: "grabowski@marpol.pl"
  password: "3621226Krzy$"
  folder: "INBOX"